apiVersion: v1
kind: Service
metadata:
  name: sping-boot-app
spec:
  type: NodePort
  selector:
    app: sping-boot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31000
